# Generated by Django 3.1.2 on 2020-10-27 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Youtube_in',
            fields=[
                ('In_idx', models.AutoField(primary_key=True, serialize=False)),
                ('view_sub', models.IntegerField(default=0)),
                ('video_nums', models.IntegerField(default=0)),
                ('male', models.IntegerField(default=0)),
                ('multisex', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Youtube_out',
            fields=[
                ('Out_idx', models.AutoField(primary_key=True, serialize=False)),
                ('contents', models.IntegerField(default=0)),
            ],
        ),
    ]
