# Generated by Django 3.1.2 on 2020-10-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_auto_20201027_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtube',
            name='contents',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
